baseURL = "http://example.org/"
languageCode = "en-us"
title = "Etomica"

[markup]
[markup.tableOfContents]
endLevel = 3
startLevel = 1


[menu]
    [[menu.main]]
        identifier = "docs"
        name = "Documentation"
        url = "/docs/"

    [[menu.main]]
        identifier = "modules"
        name = "Modules"
        url = "/modules/"

    [[menu.main]]
        identifier = "publications"
        name = "Publications"
        url = "/publications/"